services:
  - type: web
    name: telegram-mini-adshare
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    plan: free
    region: frankfurt
    runtime: python-3.10
